### ISSUE TITLE
Word Only Changes in One Place

### ISSUE THREAD

**Issue by RenSchuon** [peeley/lucy#107]
If a word is changed in any way, whether color or word, it does not change it in all the places. An example is that the word snack is in the snack folder and in the comfort folder. If it is changed in the snack folder, it does not change it everywhere, even though the same database item is being called.

**Comment by eloisab17** [comment]
The folder and board controllers both edit tiles by first retrieving the corresponding word or folder by their id in the database, which we know is unique for each tile.

I modified the controllers to print out the tile id when a tile is being edited. The snack tile in the Snack folder has a different id from the snack tile in the comfort folder, as seen below.

id for snack in Snack folder:
<img width="605" alt="image" src="https://user-images.githubusercontent.com/16232939/161871272-0a61197b-88a1-4aae-8193-663a46ca617f.png">

id for snack in Comfort folder:
<img width="612" alt="image" src="https://user-images.githubusercontent.com/16232939/161871346-c3c323d7-d764-4f3a-b8b7-c73a8c84ace0.png">

These could be different because two different snack tiles were created in the database seeder; is that the case?

**Comment by eloisab17** [comment]
Another question I have is if a user updates a word in one folder, do we want to update all the words with matching texts in all folders, even if they aren't the same database item? That way if a user has two different "Snack" tiles in the database, the word gets updated across all folders.

**Comment by RenSchuon** [comment]
only ones that are the dame database id

**Comment by RenSchuon** [comment]
This seems to be fine now

**Comment by RenSchuon** [comment]
AHHH wrong one again, it is fixed
